-- Migration: jute_prod_weaving_log — frozen per-row Process snapshot.
-- Column set mirrors weaving_day_slice_sql outer SELECT (weaving_query.py:802-822),
-- incl. spell_rank; plus source FK + SQC drift fingerprint + audit.
-- Rollback: DROP TABLE jute_prod_weaving_log;
CREATE TABLE jute_prod_weaving_log (
  weaving_log_id       INT PRIMARY KEY AUTO_INCREMENT,
  weaving_daily_id     INT NULL,
  co_id                INT NOT NULL,
  branch_id            INT NULL,
  tran_date            DATE NOT NULL,
  spell_id             INT NOT NULL,
  spell_code           VARCHAR(10) NULL,
  shift_bucket         VARCHAR(2) NULL,
  spell_rank           INT NULL,
  machine_id           INT NOT NULL,
  mech_code            VARCHAR(50) NULL,
  machine_name         VARCHAR(100) NULL,
  line_no              VARCHAR(50) NULL,
  weaving_quality_id   INT NULL,
  item_id              INT NULL,
  item_code            VARCHAR(50) NULL,
  item_name            VARCHAR(255) NULL,
  weaving_quality_code VARCHAR(50) NULL,
  weaving_quality_name VARCHAR(255) NULL,
  is_composite         TINYINT NULL,
  eb_id                INT NULL,
  beam_no              VARCHAR(50) NULL,
  cuts                 INT NULL,
  close_jugar          DECIMAL(12,3) NULL,
  less_production      DECIMAL(12,3) NULL,
  open_jugar           DECIMAL(12,3) NULL,
  jugar                DECIMAL(12,3) NULL,
  finished_length      DECIMAL(12,4) NULL,
  ozs_yds              DECIMAL(10,4) NULL,
  std_ozs_yds          DECIMAL(10,4) NULL,
  no_of_jugar_per_cut  DECIMAL(10,3) NULL,
  std_speed            DECIMAL(12,3) NULL,
  act_speed            DECIMAL(12,3) NULL,
  std_picks            DECIMAL(10,3) NULL,
  act_picks            DECIMAL(10,3) NULL,
  std_eff              DECIMAL(10,3) NULL,
  target_eff           DECIMAL(10,3) NULL,
  eff_speed            DECIMAL(12,3) NULL,
  eff_picks            DECIMAL(10,3) NULL,
  working_hours        DECIMAL(10,3) NULL,
  production_yds       DECIMAL(14,3) NULL,
  production_kg        DECIMAL(14,3) NULL,
  production_mt        DECIMAL(14,4) NULL,
  std_prod_yds         DECIMAL(14,3) NULL,
  target_prod_yds      DECIMAL(14,3) NULL,
  efficiency           DECIMAL(10,2) NULL,
  std_prod_kg          DECIMAL(14,3) NULL,
  target_kg            DECIMAL(14,3) NULL,
  sqc_pick_avg         DECIMAL(10,3) NULL,
  sqc_pick_maxdate     DATE NULL,
  active               TINYINT NOT NULL DEFAULT 1,
  updated_by           INT NULL,
  updated_date_time    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_wlog_unit (co_id, tran_date, spell_id)
);
